PR to merge forms into develop
talhawaqar/re-former pull request #1
Opened 2020-08-18 11:32 UTC by UmairAhmad125

In this project, we build a form that takes the username, email, and password of the user, validates the data, and saves in the database.
User can also update user data.

2020-08-18 23:22 UTC, lekegitrepo requested changes
### Status: Request changes :recycle:
#### Hi @UmairAhmad125 and @talhawaqar :clap: :clap:
#### Good job so far. However, you need to implement a few requirement before this project can be approved.

#### Check my comments below :point_down:

#### _Reviewed by Temitayo Adeleke_.

2020-08-18 23:22 UTC, lekegitrepo commented on app/views/users/edit.html.erb
> +  <% end %>
- **_There should be NO application logic in the views instead create a helper, logic can be encapsulated in View helpers_**

- **_There should be commented out `form` with:_**
* [x] **_uses `users_path` helper for action_**
* [x] **_uses `post` for method_**
* [x] **_uses `"UTF-8"` for ccept-charset_**
* [x] **_uses `user[<field_name>]` for input's name_**
* [x] **_uses form_authenticity_token_**

- **_There should be commented out `form_tag` that uses `label_tag`, `text_field_tag`, `email_field_tag`, `password_field_tag`_**

### Optional
* [ ] **_partial created for user form and reused in edit and new view_**

2020-08-19 18:53 UTC, uryelah requested changes
Hi **Umair Ahmad & Talha Waqar**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job with some of the fixes, but there are still some requirements from Odin project instructions missing in your project. Make sure to read the comments under this post carefully and make the needed changes.

# Required Changes 🏗️ 🐛 💡
(Check below)

-----

 **Kindly fix the pointed out issues and comments below before requesting the next code review**

------------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-08-19 18:53 UTC, uryelah commented on app/controllers/users_controller.rb
> +      redirect_to new_user_path
- [ ] You should be redirecting to `redirect_to edit_user_path` instead.

2020-08-19 18:53 UTC, uryelah commented on app/views/users/new.html.erb
> +<%# <form action="/users" method="post" accept-charset="UTF-8">
- [ ] The action used here should be the helper `users_path`

2020-08-19 18:53 UTC, uryelah commented on app/views/users/new.html.erb
> +  <input type="text" id="username" name="username"><br><br>
- [ ] The names of each input should follow the pattern `user[<field_name>]`.
- [ ] Make sure this commented out form is actually working.
You should have followed the work flow Odin project gave you, 
first make sure the form using `<form>` tag is working.
then comment it out
then make the form_tag form
make sure it's working
and the comment it out.

2020-08-19 18:53 UTC, uryelah commented on app/views/users/new.html.erb
> +<%# <%= form_tag("/users", method: "post") do %>
- [ ] Use `users_path` for the form_tag only parameter. Adding the method won't be needed then.

2020-08-20 13:05 UTC, Ispirett approved these changes
## Status Approved 👍 

Good job folks incorporating all the changes requested, you have done well.  🥇

2020-08-20 14:30 UTC, merged